// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATokIgXQYVgK6UVdJXFZQgKs6QFMEjJpw',
    appId: '1:1020394497792:web:4d085c0b9e770c879f35e5',
    messagingSenderId: '1020394497792',
    projectId: 'pupilink',
    authDomain: 'pupilink.firebaseapp.com',
    storageBucket: 'pupilink.firebasestorage.app',
    measurementId: 'G-V230844M73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9V0_s0wRXG1ZnfTf-vvoaAr_cSlHrHg',
    appId: '1:1020394497792:android:69b66aa563ff23299f35e5',
    messagingSenderId: '1020394497792',
    projectId: 'pupilink',
    storageBucket: 'pupilink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNoKJU5H9Arjsesu9oamatUmorpyZqc8',
    appId: '1:1020394497792:ios:dc01ae4d6262b9659f35e5',
    messagingSenderId: '1020394497792',
    projectId: 'pupilink',
    storageBucket: 'pupilink.firebasestorage.app',
    iosBundleId: 'com.example.schoolStaffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNoKJU5H9Arjsesu9oamatUmorpyZqc8',
    appId: '1:1020394497792:ios:dc01ae4d6262b9659f35e5',
    messagingSenderId: '1020394497792',
    projectId: 'pupilink',
    storageBucket: 'pupilink.firebasestorage.app',
    iosBundleId: 'com.example.schoolStaffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATokIgXQYVgK6UVdJXFZQgKs6QFMEjJpw',
    appId: '1:1020394497792:web:1631451aa7909e199f35e5',
    messagingSenderId: '1020394497792',
    projectId: 'pupilink',
    authDomain: 'pupilink.firebaseapp.com',
    storageBucket: 'pupilink.firebasestorage.app',
    measurementId: 'G-XRJCF1F7P5',
  );
}
